{
 "title": "Paolo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Atividade",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "/query/nedic/graph&activity_score",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Ociosidade por pacote",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "/query/nedic/graph&inactivity_score",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Atividade por Pacote",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "/query/nedic/bar", "type": "timeserie" }
   ]
  },
  {
   "title": "Horas Trabalhadas",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "/query/nedic/gauge", "type": "timeserie" }
   ]
  },
  {
   "title": "Programas mais utilizados",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "/query/nedic/table", "type": "timeserie" }
   ]
  },
  {
   "title": "Programa mais utilizado por pacote",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "target": "/query/nedic/gauge", "type": "timeserie" }
   ]
  }
 ]
}